### ISSUE TITLE
Create Server-Side Matomo Tag Manager

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#875] opened 2024-09-04 13:48 UTC
Hi team,

One recurrent request that we have for Matomo Tag Manager is "Is there a server-side version of Matomo Tag Manager?" As the answer is no, I am creating this ticket here in order to keep a record of this demand.

**Comment by snake14** [comment] 2024-09-04 21:41
Hi @Chardonneaur . Thank you for taking the time to create this issue. It appears to be a duplicate of #305 . I'll close this issue in favour of that one.

**Closed as not planned by snake14** 2024-09-04 21:41 UTC
