### ISSUE TITLE
Enhancement: Function for creating a new tag by copy/paste an existing tag 

### ISSUE THREAD

**Issue by atom-box** [matomo-org/tag-manager#636] opened 2023-06-06 19:43 UTC
_Copying and pasting tags to create new tags was requested today._

> Hello!
> We have some improvement suggestions to the platform:
>  - We would love a copy tag/trigger-function (for tag manager).

**Comment by snake14** [comment] 2023-06-06 20:54
Hi @atom-box . This sounds like a duplicate of #615 , so I'm going to go ahead and close this one.

**Closed as completed by snake14** 2023-06-06 20:54 UTC
