### ISSUE TITLE
Events in Tag Manager Do Not Appear In Behavior/Events

### ISSUE THREAD

**Issue by onairmarc** [matomo-org/tag-manager#549] opened 2022-09-30 21:20 UTC
Event's in Tag Manager are being logged to the Visits Log but are not appearing in Events report under Behavior (Behavior/Events).
Archiving runs every 15 minutes and has been run multiple times with no success getting events to appear under behavior.
Screenshots attached for reference. 

### Visitors Log
![Matomo_Visitors_Log](https://user-images.githubusercontent.com/50760632/193357508-3d74a3d5-79bb-467b-82d1-b22af45392f1.png)

### Event Categories
![Matomo_Events_Category](https://user-images.githubusercontent.com/50760632/193357505-92f9b3ac-68e2-4d9f-b109-6b78d8c53d9f.png)

### Event Actions
![Matomo_Events_Action](https://user-images.githubusercontent.com/50760632/193357503-41808cb1-19e6-4c7e-9fb3-b953d1a998f2.png)

### Event Names
![Matomo_Events_Name](https://user-images.githubusercontent.com/50760632/193357506-24ec63d7-83ff-4fc8-94aa-92e220adc68f.png)

**Comment by snake14** [comment] 2022-10-02 21:00
Hi @mbeinder . Thank you for taking the time to create this issue. Where you have events setup in Matomo Tag Manager and they're getting recorded, I would expect them to display in the Events page as well. I just confirmed in my local environment that they show up in Behaviour > Events when they get recorded, but I don't have it archiving in batches. I found a similar sounding issue on the [Matomo Forum](https://forum.matomo.org/t/goals-and-events-appear-in-visits-log-but-not-reports/44034/2), but it appears to have resolved with time.
So, I guess we just need to figure out what's going on with your setup. What version of Matomo are you running? Do you know which version of Matomo Tag Manager is installed? Is everything else getting archived properly? Do you have any logs indicating that the archiving process is completing successfully or are there errors?

**Comment by onairmarc** [comment] 2022-10-02 21:11
Thank you for your reply. After several hours, events started showing up under Behavior/Events. I am running the latest version on the stable release branch. I'm not in front of my computer right now but I can get specific information later on to help identify the root cause.

**Comment by heurteph-ei** [comment] 2022-10-03 12:30
@mbeinder I think this is the archiving period.
As archiving consumes a lot of time, it is done a few times a day, then there is some delay between the event (in log viewer) and its presence in reports...

**Comment by onairmarc** [comment] 2022-10-03 15:39
Currently Running
Matomo Core: 4.11.0
Matomo Tag Manager: Couldn't find a version number.

Archiving runs every 15 minutes but doesn't take a super long time . It's normally complete by the time the next one starts.

**Comment by snake14** [comment] 2022-10-03 20:21
@mbeinder How high do you have your `todayArchiveTimetoLive` value set to? Is it set less than 15 minutes? If not, that could be preventing today's reports from archiving as frequently as you might expect. You can find more details in the [FAQ about setting up archiving](https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/#important-tips-for-medium-to-high-traffic-websites).

**Comment by onairmarc** [comment] 2022-10-03 21:17
@snake14 it's set to 900. So right at 15 minutes.

**Comment by snake14** [comment] 2022-10-04 01:28
Hi @mbeinder . I chatted with one of our support techs and he said that it sounds like the system is working as designed and recommended that you take a look at some of the [global configs](https://github.com/matomo-org/matomo/blob/4.x-dev/config/global.ini.php#L353-L370), especially the date range one, since you were trying to view the Events using a date range. You might also try querying the [Matomo forum](https://forum.matomo.org/) if you need more guidance.

**Closed as completed by snake14** 2022-10-04 01:28 UTC
Labels: answered

**Comment by onairmarc** [comment] 2022-10-04 14:10
@snake14  Thanks for taking the time to look at this! 😄
