### ISSUE TITLE
[Feature requests|Maybe a bug] Add trigger priority and trigger order

### ISSUE THREAD

**Issue by skyhhjmk** [matomo-org/tag-manager#759] opened 2024-03-03 16:33 UTC
First of all, I have to say that my native language is Chinese, so I use Bing Translate to translate my issue content

For this issue, my requirement is to start loading another tag after it has been fully loaded, similar to a dependency

eg:

![Clip_2024-03-04_00-21-40](https://github.com/matomo-org/tag-manager/assets/78078552/443b26ea-1fb3-4700-be71-bde87e256776)

In the image above is a tag that has been created, and its trigger condition is "page view", which will insert the following code at the end of the header tag

```
<link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css">
<script src="https://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js"></script>
```
![Clip_2024-03-04_00-24-59](https://github.com/matomo-org/tag-manager/assets/78078552/0fdd67bb-c446-46d3-bdd1-bb4a0edeba0b)

I used the priority feature in the advanced settings, but this turned out to be unexpected, I thought that raising the priority would make it load as early as possible, but I seemed wrong

![Clip_2024-03-04_00-26-26](https://github.com/matomo-org/tag-manager/assets/78078552/d8ca21b8-38d4-4990-84bf-28ec91d9fff3)

Here's another tab of mine, but it's triggered like this in a production environment, but if we need to show this pop-up when the user enters the page (these are code for pop-ups), then unfortunately this is going to happen unexpectedly

![Clip_2024-03-04_00-28-22](https://github.com/matomo-org/tag-manager/assets/78078552/2c0f1320-ef1d-4b2c-a3aa-453c75e14a87)

If the trigger is changed to the same trigger as the one used by the ingested resource (in this case, "page view"), the pop-up will not appear, and an error like "function undefined" will be reported in the developer tools

**Comment by snake14** [comment] 2024-03-03 20:39
Hi @skyhhjmk . I'm sorry to hear that you're experiencing these issues. It sounds like the main issue is that your toastr.min.js file isn't loading soon enough for it to be used in your second tag. It looks like you were on the right track with the `Priority` setting, but you have it reversed. I believe that if you switch the second tag to the same trigger as the first and make your first tag Priority `1` and the second tag `2` or higher, it will ensure that the first tag executes first. Please let me know if that fixes the issue for you.

**Comment by skyhhjmk** [comment] 2024-03-04 11:08
Sorry, this method you provided doesn't seem to work

![Clip_2024-03-04_18-59-33](https://github.com/matomo-org/tag-manager/assets/78078552/e2c30995-8fb5-4255-93d2-b710eae7c148)

![Clip_2024-03-04_19-01-12](https://github.com/matomo-org/tag-manager/assets/78078552/76721c50-5036-4ef7-b2d4-72b191e7e79e)

In the red box in the image above is the label that went wrong

The content in the "js报错弹窗" is:
```
<script>
var messageOpts = {
    "closeButton": true,// 是否显示关闭按钮
    "progressBar":true,// 是否显示进度条
    "positionClass": "toast-bottom-right",// 弹出窗的位置
    "showDuration": "1000",// 显示的动画时间
    "hideDuration": "1000",// 消失的动画时间
    "timeOut": "10000",// 弹窗展现时间
    "showEasing": "linear",//显示时的动画缓冲方式
    "hideEasing": "linear",//消失时的动画缓冲方式
    "showMethod": "fadeIn",//显示时的动画方式
    "hideMethod": "fadeOut", //消失时的动画方式
    "allowHtml":false,// 允许弹窗内容包含 HTML 语言
};
toastr.options = messageOpts;

toastr.error("注意，JavaScript出现错误！如果网站有任何问题，请尝试使用Ctrl + F5 强制刷新", "错误")
</script>
```

Triggers and priorities in the "js报错弹窗" is:

![Clip_2024-03-04_19-03-06](https://github.com/matomo-org/tag-manager/assets/78078552/72c12403-122b-49bd-be0e-5b8f1636d68c)

And...

The content in the "基于toastr库的弹窗引入" is:

```
<link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css">
<script src="https://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js"></script>
```

Triggers and priorities in the "基于toastr库的弹窗引入" is:

![Clip_2024-03-04_19-05-58](https://github.com/matomo-org/tag-manager/assets/78078552/b93cb089-0d85-4a5d-ba8a-343fd09735d5)

---

Just in case I miss some of the details, here I've uploaded the full settings page for both tabs

![Clip_2024-03-04_19-07-45](https://github.com/matomo-org/tag-manager/assets/78078552/a9717ad9-c67f-4b54-97e8-dd3c099361ba)

![Clip_2024-03-04_19-06-45](https://github.com/matomo-org/tag-manager/assets/78078552/280c5228-f1e1-4b97-8c01-3ce77f284cae)

**Comment by skyhhjmk** [comment] 2024-03-04 11:16
I found that Matomo supports exporting version information, so I exported this version of JSON, hoping to help you analyze this issue, but it should be noted that since this is exported from production, I didn't change the two triggers to be consistent (and in fact they shouldn't be), but I did use the same triggers when testing in debug

[container_uMoSx32n_1.0.18.json](https://github.com/matomo-org/tag-manager/files/14480643/container_uMoSx32n_1.0.18.json)

**Comment by snake14** [comment] 2024-03-04 22:13
Hi @skyhhjmk . Thank you for all of the helpful information. I was able to reproduce the issue in my local environment. However, the the tags are executing in the correct order. The problem appears to be that the [toastr.min.js](https://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js) file doesn't actually define a variable named `toastr`. It sets `window.toastr`, so I tried that with no success. As the issue appears to be with the code JavaScript itself and not Matomo Tag Manager, I'm closing this issue. Please let me know if you feel this issue needs to be reopened.

If it's for sure a timing issue, you could try setting a value for the Fire delay setting:
![image](https://github.com/matomo-org/tag-manager/assets/11394099/05e6aa88-9e8c-404d-b1f7-4c375d47dfd7)

**Closed as completed by snake14** 2024-03-04 22:13 UTC
Labels: answered
