### ISSUE TITLE
Tag Manager doesnt update DL variable values 

### ISSUE THREAD

**Issue by dosight** [matomo-org/tag-manager#882] opened 2024-09-16 10:46 UTC
Hi!
I setup DL variables in MTM and then ran the debug mode - DLV doesnt update with event. If i publicate version and tracking GA events, still events with variables does not correctly work.

What could be the problem?

**Comment by snake14** [comment] 2024-09-16 21:29
Hi @dosight . Thank you for taking the time to create an issue. If I understand correctly, this sounds like a duplicate of the recently closed issue #304. Basically, MTM doesn't currently sync GTM dataLayer events into the MTM dataLayer. The new improvement adds a setting to allow that. The change hasn't been released yet, but will likely be included in the next Matomo release.

**Comment by dosight** [comment] 2024-09-17 07:25
Thanks for answer!
But the question is a little different - perhaps I formulated the problem incorrectly.

I create a dataLayer variable and run the debug - after the page loads, I see the required values ​​in the DLV in debug mode, but they are not updated further. DLV is supposed to react to every value change inside the dataLayer, but it doesn't.

Is this also due to the lack of full synchronization in the current version of MTM?

**Comment by AltamashShaikh** [comment] 2024-09-17 07:28
@dosight You are correct the continuous synchronization of DLV will be part of next release.

**Comment by AltamashShaikh** [comment] 2024-09-18 03:48
@dosight Closing this as we already have an issue for it and the solution is implemented too.

**Closed as not planned by AltamashShaikh** 2024-09-18 03:48 UTC
