### ISSUE TITLE
Error regenerating MTM Container during update to 4.12.x

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#565] opened 2022-11-02 20:46 UTC
When updating from an older version of Matomo to a 4.12.x version of Matomo results in the following error during the `core:update`:
```
ERROR [2022-11-02 08:05:07] 40573 There was an error while regenerating container releases: /var/www/html/matomo/core/Date.php(1144): Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information): [Query: , CLI mode: 1]
```

This error is returned after the DB migration for the 4.12.x Tag Manager update are run.

It seems that executing the `tagmanager:regenerate-released-containers` command manually after the update doesn't return the same error.

Steps to reproduce (Not yet tested):
1. Install an older version of Matomo 4 (I.e. 4.3)
2. Update to the codebase to the latest version of Matomo
3. Execute `core:update` in a terminal to see the error

**Comment by snake14** [comment] 2022-11-02 22:59
As it would take me a while to try and reproduce this, I glanced at the code. The error appears to be thrown by the `regenerateReleasedContainers` method in `plugins/TagManager/TagManager.php`. That in turn calls `$containerModel->generateContainer`. Looking at the `generateContainer` method in `plugins/TagManager/Model/Container.php`, which leads to the `enrichContainer` method, it looks like somehow they had a container that had a invalid date stored in either `created_date` or `updated_date`. As the database restricts those two columns to datetime values, I'm not really sure how that would happen.
@Starker3 Was any more of the stack trace available or just the section included above?

**Comment by MatomoForumNotifications** [comment] 2022-11-03 13:08
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/error-while-upgrading-database-4-4-1-4-12-3/48071/2

**Comment by Starker3** [comment] 2022-11-03 23:37
@snake14 Only the error message was included. We might be able to get more information if we were to setup a 4.3 install for example and enable debug logging before running an update. But we would likely need to also create a container and some tags in such a new install in order to trigger it.

**Comment by snake14** [comment] 2022-11-04 00:58
@elabuwa @justinvelluppillai What's the best course of action here? We need to validate/reproduce the issue, but I don't want to derail my sprint progress by taking the time to setup a Matomo 4.3 install.

**Comment by AltamashShaikh** [comment] 2022-11-07 08:57
Hey @Starker3 
I setup a fresh Matomo 4.3.1 on my local
Generated 1-2 pageviews and setup a TagManager Tags,Variable and Trigger

Update to latest version and later ran `core:update` and I can see it executed successfully
```
./console core:update -vvv

    *** Update ***

    Database Upgrade Required

    Your Matomo database is out-of-date, and must be upgraded before you can continue.

    Matomo database will be upgraded from version 4.3.1 to the new version 4.12.3.

    The following plugins will be updated: TagManager.

    *** Note: this is a Dry Run ***

    ./console config:set --section="General" --key="login_allow_logme" --value="1"
    ALTER TABLE `matomo_session` CHANGE `data` `data` MEDIUMTEXT;
    ./console plugin:activate "CoreVue"
    ALTER TABLE `matomo_user` ADD COLUMN `idchange_last_viewed` INTEGER UNSIGNED NULL;
    CREATE TABLE `matomo_changes` (`idchange` INT(11) NOT NULL AUTO_INCREMENT, `created_time` DATETIME NOT NULL, `plugin_name` VARCHAR(255) NOT NULL, `version` VARCHAR(20) NOT NULL, `title` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `link_name` VARCHAR(255) NULL, `link` VARCHAR(255) NULL, PRIMARY KEY ( `idchange` )) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
    ALTER TABLE `matomo_changes` CHANGE `plugin_name` `plugin_name` VARCHAR(60) NOT NULL;
    ALTER TABLE `matomo_changes` DROP INDEX `unique_plugin_version_title`;
    ALTER TABLE `matomo_changes` ADD UNIQUE KEY unique_plugin_version_title (`plugin_name`, `version`, `title` (100));
    ALTER TABLE `matomo_user` ADD COLUMN `invite_status` ENUM('accept','pending','decline','expired') DEFAULT 'accept';
    ALTER TABLE `matomo_user` DROP COLUMN `invite_status`;
    ALTER TABLE `matomo_user` ADD COLUMN `invite_token` VARCHAR(191) DEFAULT null;
    ALTER TABLE `matomo_user` ADD COLUMN `invited_by` VARCHAR(100) DEFAULT null;
    ALTER TABLE `matomo_user` ADD COLUMN `invite_expired_at` TIMESTAMP null DEFAULT null;
    ALTER TABLE `matomo_user` ADD COLUMN `invite_accept_at` TIMESTAMP null DEFAULT null;
    ALTER TABLE `matomo_site` ADD COLUMN `excluded_referrers` TEXT NOT NULL AFTER `excluded_user_agents`;
    ALTER TABLE `matomo_user` ADD UNIQUE KEY uniq_email (`email`);
    ALTER TABLE `matomo_user` ADD COLUMN `invite_link_token` VARCHAR(191) DEFAULT null;
    ALTER TABLE `matomo_tagmanager_tag` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;
    ALTER TABLE `matomo_tagmanager_trigger` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;
    ALTER TABLE `matomo_tagmanager_variable` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;

    *** End of Dry Run ***

A database upgrade is required. Execute update? (y/N) y

Starting the database upgrade process now. This may take a while, so please be patient.

    *** Update ***

    Database Upgrade Required

    Your Matomo database is out-of-date, and must be upgraded before you can continue.

    Matomo database will be upgraded from version 4.3.1 to the new version 4.12.3.

    The following plugins will be updated: TagManager.

    The database upgrade process may take a while, so please be patient.

  Executing ./console config:set --section="General" --key="login_allow_logme" --value="1"... Done. [1 / 20]
  Executing ALTER TABLE `matomo_session` CHANGE `data` `data` MEDIUMTEXT;... Done. [2 / 20]
  Executing ./console plugin:activate "CoreVue"... Done. [3 / 20]
  Executing ALTER TABLE `matomo_user` ADD COLUMN `idchange_last_viewed` INTEGER UNSIGNED NULL;... Done. [4 / 20]
  Executing CREATE TABLE `matomo_changes` (`idchange` INT(11) NOT NULL AUTO_INCREMENT, `created_time` DATETIME NOT NULL, `plugin_name` VARCHAR(255) NOT NULL, `version` VARCHAR(20) NOT NULL, `title` VARCHAR(255) NOT NULL, `description` TEXT NOT NULL, `link_name` VARCHAR(255) NULL, `link` VARCHAR(255) NULL, PRIMARY KEY ( `idchange` )) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;... Done. [5 / 20]
  Executing ALTER TABLE `matomo_changes` CHANGE `plugin_name` `plugin_name` VARCHAR(60) NOT NULL;... Done. [6 / 20]
  Executing ALTER TABLE `matomo_changes` DROP INDEX `unique_plugin_version_title`;... Done. [7 / 20]
  Executing ALTER TABLE `matomo_changes` ADD UNIQUE KEY unique_plugin_version_title (`plugin_name`, `version`, `title` (100));... Done. [8 / 20]
  Executing ALTER TABLE `matomo_user` ADD COLUMN `invite_status` ENUM('accept','pending','decline','expired') DEFAULT 'accept';... Done. [9 / 20]
  Executing ALTER TABLE `matomo_user` DROP COLUMN `invite_status`;... Done. [10 / 20]
  Executing ALTER TABLE `matomo_user` ADD COLUMN `invite_token` VARCHAR(191) DEFAULT null;... Done. [11 / 20]
  Executing ALTER TABLE `matomo_user` ADD COLUMN `invited_by` VARCHAR(100) DEFAULT null;... Done. [12 / 20]
  Executing ALTER TABLE `matomo_user` ADD COLUMN `invite_expired_at` TIMESTAMP null DEFAULT null;... Done. [13 / 20]
  Executing ALTER TABLE `matomo_user` ADD COLUMN `invite_accept_at` TIMESTAMP null DEFAULT null;... Done. [14 / 20]
  Executing ALTER TABLE `matomo_site` ADD COLUMN `excluded_referrers` TEXT NOT NULL AFTER `excluded_user_agents`;... Done. [15 / 20]
  Executing ALTER TABLE `matomo_user` ADD UNIQUE KEY uniq_email (`email`);... Done. [16 / 20]
  Executing ALTER TABLE `matomo_user` ADD COLUMN `invite_link_token` VARCHAR(191) DEFAULT null;... Done. [17 / 20]
  Executing ALTER TABLE `matomo_tagmanager_tag` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;... Done. [18 / 20]
  Executing ALTER TABLE `matomo_tagmanager_trigger` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;... Done. [19 / 20]
  Executing ALTER TABLE `matomo_tagmanager_variable` ADD COLUMN `description` VARCHAR(1000) NOT NULL DEFAULT '' AFTER `name`;... Done. [20 / 20]

Matomo has been successfully updated!
```

**Comment by AltamashShaikh** [comment] 2022-11-07 09:02
@Starker3 The best thing we can do is ask the user to regenerate the container and check if it still throws the error or the TagManager works as expectedly

**Comment by Starker3** [comment] 2022-11-08 20:13
> @Starker3 The best thing we can do is ask the user to regenerate the container and check if it still throws the error or the TagManager works as expectedly

Thanks for checking Altamash. It's interesting to see that with your update the command to regenerate released containers didn't execute (At least not according to the `core:update` output).
Is there certain circumstances where the `core:update` would have executed the `regenerate-released-containers` command? Maybe it's only reproducible in the case where that would happen.

**Comment by AltamashShaikh** [comment] 2022-11-23 06:41
@Starker3 I tried again but no luck in reproducing.

@tsteur Do you have any idea why this will fail ?

**Comment by tsteur** [comment] 2022-11-23 19:26
@AltamashShaikh no idea why it would fail. Maybe they can share what MySQL they are using, the content of their tag manager tables, and what SQL mode they are using (although maybe we are forcing a specific mode). 

We haven't seen similar reports though so this might be an edge case.

**Comment by AltamashShaikh** [comment] 2022-11-24 09:26
@Starker3 Can you ask for the details ?

**Comment by Starker3** [comment] 2022-11-28 03:31
I think we had 3 or 4 users in total that reported this error.

I tried as well to quickly reproduce using a fresh install and wasn't able to reproduce the issue.
Since its a temporary issue (The tag manager container would regenerated anyway again) maybe we can close this issue if we're not getting any more reports for it?

**Comment by AltamashShaikh** [comment] 2022-11-28 05:19
@Starker3 Closing this ticket for now, we can reopen if we have more such cases

**Closed as completed by AltamashShaikh** 2022-11-28 05:19 UTC
