### ISSUE TITLE
Call for CustomJsTracker when it is not present

### ISSUE THREAD

**Issue by mikkeschiren** [matomo-org/tag-manager#241] opened 2020-04-30 05:46 UTC
I have not digged into this yet - but in a installation were we are not using CustomJsTracker, TagManager still try to use it, which make Matomo crash when we regenerate tags.

**Comment by tsteur** [comment] 2020-04-30 06:00
Cheers @mikkeschiren marking this for now as duplicate of https://github.com/matomo-org/matomo/issues/15884

**Closed as completed by tsteur** 2020-04-30 06:00 UTC
Labels: duplicate, not-in-changelog
