### ISSUE TITLE
[Feature request] Call variable in custom JS variables

### ISSUE THREAD

**Issue by SW-Vincent** [matomo-org/tag-manager#706] opened 2023-10-20 14:03 UTC
Although we can already use variables within custom HTML tags, we cannot use a variable within custom Javascript variable.
This would make a fine addition to the tag manager features !

Also, it would be nice to have a "select variable" button within custom HTML tags just as there is already within Matomo tag templates.
- - - -
Edit : there is already a "select variable" button within custom HTML tags

**Comment by snake14** [comment] 2023-10-23 21:15
Hi @SW-Vincent . Thank you for the suggestion. I'm going to close this issue as it appears to be a duplicate of #212 .

**Closed as completed by snake14** 2023-10-23 21:15 UTC
Labels: duplicate
