### ISSUE TITLE
idSite trough lookup table failing to load

### ISSUE THREAD

**Issue by Mepherotus** [matomo-org/tag-manager#226] opened 2020-02-18 16:04 UTC
after following the guide:
https://matomo.org/docs/tag-manager/#advanced-variables-settings-default-value-lookup-table

most of the times (but not always, could it be a race condition?) I end up with a request to matomo that doesn't contain an idSite in the request:
...&idsite=&...

weirdly enough it's happening only during EEcomerce calls

    _paq.push(['addEcommerceItem', '999', 'foo, 'bar', 999, 1]);
    _paq.push(['trackEcommerceOrder', '999999', 99]);

Matomo version: 3.13.2

**Comment by Mepherotus** [comment] 2020-02-18 16:49
small update, even when i force the Matomo idSite to 1 in the tag manager configuration I have the same behavior (the idsite is still null in the Tracking URL)

**Comment by tsteur** [comment] 2020-02-18 21:01
Is there any chance you could send us the URL where we can reproduce this and / or export the container configuration so we can try to reproduce it? Our email is hello at matomo dot org. If there's an URL where we can quickly debug that be appreciated since it would make it easy for us to see what's happening. Cheers

**Comment by Mepherotus** [comment] 2020-02-19 09:27
I can confirm that's a race condition, by running:

	<script>
	    _paq.push(['addEcommerceItem', '999', 'foo', 'bar', 999, 1]);
            _paq.push(['trackEcommerceOrder', '9999993', 99]);
            console.log("Hello");
	    setTimeout(() => {  
            _paq.push(['addEcommerceItem', '999', 'foo', 'bar', 999, 1]);
            _paq.push(['trackEcommerceOrder', '9999994', 99]);
            console.log("World");
	     }, 2000);
	</script>

the 1st request doesn't contain the idSite parameter and fails while the second does and succeeds 

EDIT:
I've sent you a static page to reproduce the error (you can just change the order ID and see the result)

**Comment by tsteur** [comment] 2020-02-19 20:12
Cheers, I can reproduce this on the link you shared.

Basically, what is happening, Matomo Tag Manager is adding the first tracker using

`Matomo.addTracker(trackerUrl, undefined)`

This triggers `createFirstTracker(matomoUrl, siteId)`.

This causes all previously registered `_paq.push` to be evaluated including ecommerce.

At this time the `idSite` is not set yet because we are setting the idSite only after cookies etc are configured see https://github.com/matomo-org/tag-manager/pull/158

I reckon we will want to fix that in Tag Manager and can't really fix it in Matomo core. It's like we want to back up `window._paq` before initialising the first tracker, then add the tracker, then reapplying all previously registered _paq.push calls. 

@Mepherotus in the meantime you could work around this probably by setting idSite manually like 

`_paq.push(['setSiteId', 1]); _paq.push(['addEcommerceItem', '999', 'foo', 'bar', 999, 1]);`

Assuming your idSite is for example `1`.

There is also https://matomo.org/faq/tag-manager/faq_35847/ but it doesn't seem quite complete because technically you'd need to make sure that custom event is triggered after the Matomo Tag has been initialised.

**Comment by Mepherotus** [comment] 2020-02-20 10:04
works! her's the workaround that we're deploying:

`

var getDomainConfig = (domain) => {
--
  | switch (domain) {
  | case 'travelcircus.de':
  | return 1;
  | case 'tcsrv.net':
  | return 2;
  | case 'travelcircus.sandbox':
  | return 3;
  | case 'travelcircus.nl':
  | return 4;
  | case 'travelcircus.be':
  | return 5;
  | case 'urlaubsguru.de':
  | return 6;
  | case 'holidayguru.nl':
  | return 7;
  | case 'holidayguru.ch':
  | return 8;
  | case 'urlaubsguru.at':
  | return 9;
  | default:
  | return 1;
  | }
  | };
  | var mtm_domain = window.location.hostname.replace(/^.+\.([^.]+\.[^.]+)$/, '$1');
  | var siteId = getDomainConfig(mtm_domain);
  |  
  | console.log("domain: " + mtm_domain);
  | console.log("siteId: " + siteId);
  | _paq.push(['setSiteId', siteId]);



`

**Comment by Mepherotus** [comment] 2020-02-20 10:13
Works! here's the workaround we're deploying 

	var getDomainConfig = (domain) => {
		switch (domain) {
			case 'a.de':
				return 1;
			case 'a.net':
				return 2;
			case 'a.sandbox':
				return 3;
			case 'a.nl':
				return 4;
			case 'a.be':
				return 5;
			case 'b.de':
				return 6;
			case 'b.nl':
				return 7;
			case 'b.ch':
				return 8;
			case 'b.at':
				return 9;	
			default:
				return 1;
			}
		};
	var mtm_domain = window.location.hostname.replace(/^.+\.([^.]+\.[^.]+)$/, '$1');
	var siteId = getDomainConfig(mtm_domain);
	
	console.log("domain: " + mtm_domain);
	console.log("siteId: " + siteId);
	_paq.push(['setSiteId', siteId]);

**Comment by tsteur** [comment] 2020-10-29 19:32
This should be fixed now in Matomo 4

**Closed as completed by tsteur** 2020-10-29 19:32 UTC
Labels: Bug
