### ISSUE TITLE
Tag is fired even though it's blocked - runtime/priority issue?

### ISSUE THREAD

**Issue by ben-dw** [matomo-org/tag-manager#263] opened 2020-08-11 12:54 UTC
Hi there,
I have created a tag "et all pageviews" with a trigger "pageview all pages" and a blocking trigger "pageview onlineservice".
The trigger "pageview onlineservice" will be fired if the page path contains "onlineservice".

Currently the tag "et all pageviews" will always by fired even though the URL contains "onlineservice". 
The debug mode might show the problem.
1. Trigger: pageview all pages
1. Event: Tag: et all pageviews
...
10. Trigger: pageview onlineservice

How can I fix this issue? I don't want to use a time delay.

**Comment by tsteur** [comment] 2020-08-11 20:45
@ben-dw thanks for creating the issue. Is there any chance you could send us a link to a site where we can reproduce this? Or ideally send us the JS file for the container and simple HTML example to reproduce this? If you don't want to share here or email is hello at matomo.org. Just comment here in case you send an email.

**Comment by ben-dw** [comment] 2020-08-12 06:45
@tsteur I have send an email :)

**Comment by tsteur** [comment] 2020-08-13 01:37
Thanks @ben-dw I replied by email.

**Comment by ben-dw** [comment] 2020-08-13 06:14
Thank you! I've send you an update via email @tsteur

**Comment by tsteur** [comment] 2020-08-13 23:02
Created a PR @ben-dw

**Comment by heurteph-ei** [comment] 2021-04-13 15:39
Is this issue closed now, as there was #266? 
@snake14?

**Comment by snake14** [comment] 2023-04-06 01:47
That's a good question @heurteph-ei . It looks like the PR was merged. @tsteur can this issue be closed because the PR was merged?

**Comment by tsteur** [comment] 2023-04-06 02:01
Possibly. I think we were maybe waiting for the issue creator to confirm this issue resolved it. We could close it though and if it's still an issue someone can always reopen it or create a new issue

**Comment by snake14** [comment] 2023-04-06 02:15
Thank you. Sounds good. Closing the issue.

**Closed as completed by snake14** 2023-04-06 02:15 UTC
Labels: Bug, not-in-changelog
