### ISSUE TITLE
Wrong URL in Matomo after moving site to subdomain

### ISSUE THREAD

**Issue by diginote** [matomo-org/tag-manager#802] opened 2024-06-10 13:47 UTC
Hello,

we started tracking in matomo tag manager for sites on a domain without a ‘www.’ subdomain (e.g. example.com). Later, all pages had to move to the subdomain ‘www.’ (e.g. www.example.com). Unfortunately, the ‘www.’ is still not listed in the visits in Matomo. Have we forgotten to update something?

**Comment by snake14** [comment] 2024-06-10 21:23
Hi @diginote . Thank you for taking the time to create this issue. I'm sorry to hear that you're experiencing complications. Is the issue that the visits aren't being tracked at all or that the subdomain isn't showing up in the visits log?

If the issue is that the visits are being filtered out and not tracked due to the subdomain, you probably want to check the trigger that is assigned to your Matomo Analytics tag and make sure that it's not filtering  by domain.

**Comment by diginote** [comment] 2024-06-13 18:42
Hi @snake14.
The visits are tracked but the tooltip shows the old domain (without the www. subdomain). I was expecting the www. to be included in the url after moving to the new domain.

**Comment by snake14** [comment] 2024-06-13 22:14
Hi @diginote . I'm glad that the requests are being tracked. It's odd that it's not showing the URL that you are expecting. I'm pretty sure that Matomo is supposed to show the full URL, including protocol like https. Does your web server (Apache, NGINX, Tomcat, ...) use a wildcard and direct all subdomains to the same domain? Maybe the www is being removed before the tracking request is sent to Matomo. You might watch the Network tab in your browser's dev tools to see what URL is sent when tracking requests are sent to your Matomo server. Like this example request in my test site:
![image](https://github.com/matomo-org/tag-manager/assets/11394099/1442da79-6c16-44ea-abee-c0573282221f)

**Comment by AltamashShaikh** [comment] 2024-06-14 01:39
@snake14 @diginote I think that is expected, due to how the URLs are stored under `log_action` table, @sgiehl Correct me if I am wrong

**Comment by diginote** [comment] 2024-06-14 05:36
Hi. I try to visualize my problem with an example:

This is my example request:
https://my.matomo.com/js/?action_name=StartPage&idsite=10&rec=1&r=243754&h=7&m=14&s=58&url=https://www.example.com/start&_id=&_idn=1&send_image=0&_refts=0&dimension1=1&dimension2=1&dimension3=de&pv_id=ubC56s&pf_net=23&pf_srv=1&pf_tfr=18&pf_dm1=97&uadata={}&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=1878x1149

Before moving to the www. subdomain the url was https://example.com. Now we are moved to the www. sudomain, the new domain is like in the request https://**www**.example.com. However, I do not see the change of domain in Matomo.

![grafik](https://github.com/matomo-org/tag-manager/assets/4537971/c912020a-b26c-459e-b783-c0bd23e485a5)

**Comment by AltamashShaikh** [comment] 2024-06-14 13:58
@diginote We checked internally and that's expected all urls with and without `www.` are handled as same and hence you see it without `www.`

**Comment by diginote** [comment] 2024-06-20 15:51
OK, but sometimes the »www.« subdomain is present but why? It also confuses our matomo users because we always redirect non www.... calls to the www... calls. Is there somewhere in matomo a way to configure that the "www." sudomain is always displayed when this is called?

**Comment by atom-box** [comment] 2024-06-26 17:03
Hi @diginote 
Maybe check that your domain/subdomain are not listed in 
Matomo interface >> ⚙️ >> Measurables >> Manage >> edit-pencil-icon >> "urls"

Matomo uses that setting to remove the domain from the path. If you list nothing there, Matomo usually shows the full path. (If you leave it blank, Matomo seems to repopulate it, so confirm that it saved correctly. My workaround for that: I ended up saving a dummy address there to prevent Matomo from autopopulating that field.)

**Comment by diginote** [comment] 2024-07-02 14:25
@atom-box Thanks for the advice. I have checked the options you mentioned.
The domains were not listed in the measurables.
Although I then add the urls (with and without www subdomain) to the measurables in the UI, only the www subdomain is removed. The following main domain with the path is not removed.
At the moment I don't understand how this works.

**Comment by dr2okevin** [comment] 2024-08-29 08:35
I have the problem the other way around. For the Startpage Matomo always shows a www subdomain, even tho the page dosen't have a www subdomain. (More technical, the www subdomain is a different vhost with a 301 redirect to the variant without www)

Furthermore, www is a subdomain like any other, and should never be treated the same as no subdomain. I could serve completely different content over the www subdomain.

And in my case it is already the subdomain of a subdomain. So a visitor to https://subdomain.example.org/ gets logged as https://www.subdomain.example.org but a visit to https://subdomain.example.org/subpage.html gets correctly logged as https://subdomain.example.org/subpage.html

I have nowhere configured anything with www

**Comment by AltamashShaikh** [comment] 2024-10-18 09:02
@dr2okevin Apologies for late reply, we checked internally and Matomo handles domains with and without `www.`  prefix the same, whatever is tracked first will sort of "win". So if a url is tracked with `www.`  first, the one without won't be shown anywhere and vise versa.

**Comment by diginote** [comment] 2024-10-18 09:57
@AltamashShaikh This explains the current behaviour. However, does it make sense to display or not display a subdomain according to a certain set of rules? Why is it simply not adopted as it is called up by the user or displayed in the user's browser? Is there a reason why you try to hide subdomains or apply the principle that the first tracked URL determines what is displayed forever, even if the domain changes in the future (e.g. website is first delivered without www subdomain and later with www or vice versa)?

**Comment by AltamashShaikh** [comment] 2024-10-23 02:36
@diginote Can you create a matomo-core issue for this ? as its related to how Matomo core treats the URL, you can create a issue [here](https://github.com/matomo-org/matomo/issues/new/choose)

**Comment by diginote** [comment] 2024-10-23 14:51
I hope this is ok: https://github.com/matomo-org/matomo/issues/22710

**Comment by AltamashShaikh** [comment] 2024-10-24 02:16
Yes @diginote :+1:

**Comment by AltamashShaikh** [comment] 2024-10-30 03:36
@diginote We are closing this as we now have a core issue for this.

**Closed as not planned by AltamashShaikh** 2024-10-30 03:36 UTC
