### ISSUE TITLE
Priority of tags does not apply if trigger is different

### ISSUE THREAD

**Issue by DarkLink571** [matomo-org/tag-manager#786] opened 2024-05-03 08:52 UTC
When two or more tags are fired at the same time, the priority of the tags is not used if the tags don't have the same trigger.

Steps to reproduce:
- Create two identical (except for the name) triggers.
- Create two tags, each uses one of the triggers.
- Set the priority of the tags to different values.
- Open the preview and trigger both triggers.
- Switch the priority of the two tags.
- Open preview again and trigger both triggers again.
- The order of the tags will be the same in each case.

I guess this is not the expected behaviour and I haven't found an open issue for this yet.

**Comment by snake14** [comment] 2024-05-05 21:36
Hi @DarkLink571 . Thank you for taking the time to create this issue. Reading through your description, I would say that's actually the expected behaviour. If both tags used the same trigger and the priority wasn't honoured, that would be an issue. However, if they use different triggers, there isn't really a clear way to enforce the priority as they could be triggered at very different times. Even being triggered at relatively the same time, since the triggers were different, the tags are processed separately. Do you have any insights on this @AltamashShaikh ?

**Comment by AltamashShaikh** [comment] 2024-05-06 07:03
@snake14 You are correct, @DarkLink571 Can you please elaborate more on what seems to be incorrect for you ?

**Comment by DarkLink571** [comment] 2024-05-14 07:22
Hi @snake14 and @AltamashShaikh
If the two different triggers will trigger under the same conditions, for example when I use two pageview triggers but with different extra conditions, I would assume all tags that should be fired on a pageview will be ordered by priority, independent of the trigger that triggers them.

**Comment by AltamashShaikh** [comment] 2024-05-14 07:43
@DarkLink571 Can you share the screenshot of 2 triggers ?

**Comment by DarkLink571** [comment] 2024-05-24 07:36
<img width="1236" alt="ConversionPageview" src="https://github.com/matomo-org/tag-manager/assets/117860602/a9e4bf3f-5a11-41d8-bf49-72b1d1dabd22">
<img width="432" alt="ConversionTag" src="https://github.com/matomo-org/tag-manager/assets/117860602/c03911ff-96df-43d9-b0f8-1402466dc4ad">
<img width="1234" alt="Pageview" src="https://github.com/matomo-org/tag-manager/assets/117860602/e298016e-a06c-4442-a6d6-58d7ed12da27">
<img width="428" alt="SetupTag" src="https://github.com/matomo-org/tag-manager/assets/117860602/8854308f-34de-4bfd-a6b4-122503192bbc">

Here is an example of what I expected to work. The setup tag should fire on every page and it is important for it to always fire before the conversion tag.

**Comment by AltamashShaikh** [comment] 2024-05-24 14:39
@DarkLink571 
I just tried this created a function in my HTML file where we have included the MatomoTagManagerCode.
```
<script>
    function trackCustom(trackingType) {
        console.log(trackingType, 'trackingType');
    }
</script>
```

Now created 2 tags to fire on `pageView` trigger
1. Custom HTML should fire first (priority: 1) -> `trackCustom('pageView');`
2. Custom HTML should fire second (priority: 10) -> `trackCustom('conversion');`

I can see "Custom HTML should fire first" being executed first and "Custom HTML should fire second" after that.

![Screenshot from 2024-05-24 20-03-59](https://github.com/matomo-org/tag-manager/assets/14902277/137bb0db-d63a-4b30-9a8d-8e0ae4728fbb)

![Screenshot from 2024-05-24 20-08-17](https://github.com/matomo-org/tag-manager/assets/14902277/c524fc5c-3259-4a08-a165-f6ed44c0fe84)

Just FYI. the priority should be lower if you want it to execute first.

**Comment by AltamashShaikh** [comment] 2024-05-24 14:45
Custom HTML should fire first
![tag_first](https://github.com/matomo-org/tag-manager/assets/14902277/61d3dde8-a41b-4ec3-a7e9-0cd15612e66f)

Custom HTML should fire second
![tag_second](https://github.com/matomo-org/tag-manager/assets/14902277/dc9c8cec-ae6f-40ca-a265-1e24eb5a669e)

**Comment by DarkLink571** [comment] 2024-05-27 16:12
This is not exactly what I meant. In this example, the setup of the tracking function should also be done in the Tag Manager and not be hardcoded. The pageview tracking may be included in this snippet (e.g. in some Google snippets the gtag is loaded and used in the same code-block). I left out the pageview tracking since it wasn't important for the example.

The important part is: Two different tags may fire on the same event but not the same trigger. The order of the tags cannot be controlled with the priority. In the example I gave, an error may occur because the tracking function is not defined despite the tag loading the function triggers on the same event and has a higher priority.

**Comment by AltamashShaikh** [comment] 2024-05-28 01:26
@DarkLink571 If its a different trigger, even though the functionality is same, it won't work the way you are saying, we would recommend you to trigger the 2nd tag on a `customEvent` trigger and fire the `customEvent` after the first tag is fired.

**Comment by snake14** [comment] 2024-06-13 03:47
Hi @DarkLink571 . We are closing this issue as we won't be changing how it currently works.

**Closed as not planned by snake14** 2024-06-13 03:47 UTC
