### ISSUE TITLE
UX issue: impossible to use the drop down menu for variables in Trigger when using Google Chrome

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#796] opened 2024-05-18 13:07 UTC
Hi Team,

When using Google Chrome it is not possible to access the variables within the drop down menu of triggers unless we use the search box.
This UX bug does not appear with Mozilla Firefox.
In order to reproduce this bug:
1 - Go to MTM with Google Chrome
2 - Create a new trigger
3 - try to pick up the click text variable from the drop down menu
Here is a video showing the bug:

https://github.com/matomo-org/tag-manager/assets/28002238/52567966-bda3-415d-9d5e-649215c4879a

**Comment by Starker3** [comment] 2024-05-19 20:46
I could reproduce this in Firefox. The important thing to note:
This bug only appears when editing a trigger from the Tag Edit/Create screen. Editing or creating the trigger directly there is no issue. (Click the edit button on the trigger after selecting it for a tag)

**Comment by snake14** [comment] 2024-05-19 21:27
Thank you for creating this issue @Chardonneaur . Thank you for reproducing @Starker3 . I'm unable to reproduce even when clicking the trigger edit button while editing a tag. I tried Brave, Firefox, and Chrome. Is the issue that you can't click to select an option or that you can't drag and drop? Clicking works on all the browsers I tested and drag/drop didn't work on any.

**Comment by Stan-vw** [comment] 2024-05-19 21:55
I believe I figured out the issue: scroll has a background/foreground problem, but clicks in the dropdown work fine.

Here you can see that the list isn't long enough on the pop-over, but the scroll works on the background instead of the foreground/pop-over:
https://github.com/matomo-org/tag-manager/assets/52564377/e6b61bec-7af5-46b7-842c-d06861239071

When scroll is not needed, you can click on the Click Text variable:
https://github.com/matomo-org/tag-manager/assets/52564377/0986a308-5470-4e06-95eb-c8b33a63f99d

@snake14 can you try to reproduce this?

**Comment by Stan-vw** [comment] 2024-05-20 01:17
Whilst we'll try to solve this bug shortly, here's a workaround in case you are adding triggers through this workflow and know exactly which one you want:
https://github.com/matomo-org/tag-manager/assets/52564377/5c658bb6-50a7-48f5-ad9f-3c8059797616

Alternatively, you can simply create the trigger through "Create trigger", the scroll problem doesn't seem to be applicable there 👍

**Comment by snake14** [comment] 2024-05-20 01:53
Thank you @Stan-vw . I see what you mean, and I can reproduce locally. This may need to be fixed in core, since it appears to be an issue with the expandable select component getting cut off by the modal.

**Comment by AltamashShaikh** [comment] 2024-09-25 01:55
@Chardonneaur This should be fixed in the next core release.

**Closed as completed** 2024-09-25 03:30 UTC
Labels: Bug
