### ISSUE TITLE
Tag priority is not updated but reset

### ISSUE THREAD

**Issue by BobOtike** [matomo-org/tag-manager#472] opened 2022-04-11 18:40 UTC
When creating a new tag, the priority value is not persisted anymore. No matter which value I use, it always shows 999 after I click _Update_ and the page reloads.

When editing an existing tag, the priority value is reset to 999 after a click on _Update_. 

I checked in the console and found that there is no value for the `priority`  in the query parameters. This is what an example looks like:

```
fetch("https://xxx.matomo.cloud/index.php?date=2022-04-04,2022-04-10&module=API&format=json&idTag=480&method=TagManager.updateContainerTag&idContainer=XXXXXXXX&idContainerVersion=1&type=CustomHtml&name=XXX&startDate=&endDate=&fireLimit=once_page&fireDelay=0&segment=&idSite=1&period=range", {
  "headers": {
    "accept": "application/json, text/javascript, */*; q=0.01",
    "accept-language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
    "cache-control": "no-cache",
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "pragma": "no-cache",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-requested-with": "XMLHttpRequest"
  },
  "referrer": "https://xxx.matomo.cloud/index.php?module=TagManager&action=manageTags&idSite=1&period=range&date=previous7&idContainer=XXXXXXXX",
  "referrerPolicy": "same-origin",
  "body": "token_auth=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&force_api_session=1&parameters%5BcustomHtml%5D=%3Cscript%3E%3C%2Fscript%3E&parameters%5BhtmlPosition%5D=headEnd&fireTriggerIds%5B%5D=346",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

If I go ahead and add `priority=100` to the query parameters of the `fetch` from above, the value gets updated properly. Seems like when constructing the API call, the value for `priority` is not being properly populated.

I am using Matomo Cloud with presumably the latest version of Matomo (I don't know where to check that).

**Comment by justinvelluppillai** [comment] 2022-04-11 20:01
Thanks for reporting @BobOtike. @AltamashShaikh is this possibly a regression?

**Comment by AltamashShaikh** [comment] 2022-04-11 23:23
@BobOtike This is a duplicate of #459 and it was fixed via #460 
The fix would be released with Matomo 4.9.

**Closed as completed by AltamashShaikh** 2022-04-11 23:23 UTC

**Comment by AltamashShaikh** [comment] 2022-04-11 23:26
@BobOtike Link on How to check your Matomo version - https://matomo.org/faq/how-to/how-do-i-know-which-version-of-matomo-i-am-using/#matomocloud

**Comment by AltamashShaikh** [comment] 2022-04-11 23:26
currently Matomo cloud is on 4.8.0
