### ISSUE TITLE
Tags - Update button disabled after changing settings

### ISSUE THREAD

**Issue by ben-dw** [matomo-org/tag-manager#451] opened 2022-03-11 08:09 UTC
Hi folks,
the update button is still disabled if I change settings within a Tag (eg. Event Category name). It is only enabled if I change the tag name or use a different trigger.

**Comment by sgiehl** [comment] 2022-03-11 08:24
that seems to be kind of a duplicate of #446

**Comment by ben-dw** [comment] 2022-03-11 08:28
Yes!

**Closed as completed** 2022-03-11 08:28 UTC
Labels: duplicate
