### ISSUE TITLE
Bug - Drop down menu not working when editing a trigger

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#904] opened 2024-10-05 13:50 UTC
Hi Team,

When one wants to assign a variable to a trigger, the drop down menu is not working properly:
![Screenshot from 2024-10-05 15-48-14](https://github.com/user-attachments/assets/fed9e97d-78cc-4123-8c3c-6f84b6bee10b)
It would be nice to fix this display bug (Firefox) because it is making web analysts totally crazy.
To reproduce it, access to a tag, edit the associated trigger and try to assign a variable, you will see normally the variable bug display menu:

https://github.com/user-attachments/assets/f62c5271-a25d-4b21-8469-e072d4b9d760

**Comment by Stan-vw** [comment] 2024-10-06 20:02
Seems like a duplicate of https://github.com/matomo-org/tag-manager/issues/796 which should be fixed in the next version 👍

**Closed as completed by Stan-vw** 2024-10-06 20:02 UTC
