### ISSUE TITLE
Preview mode blocking footer/lower page elements

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#448] opened 2022-03-11 02:07 UTC
I'm not sure if this issue was something that started recently, I never noticed it specifically before.
But when preview mode is enabled and the preview mode overlay is showing on the page, it blocks elements in the footer/lower page area.

For example a page without the preview mode:
![image](https://user-images.githubusercontent.com/20905821/157787982-a2a6b01b-da2f-4530-b451-850f9d3350df.png)

And with preview mode enabled:
![image](https://user-images.githubusercontent.com/20905821/157788027-ad7475a0-29fc-4b43-858e-5fff821f285d.png)
(Notice that the scroll bar is all the way down)

In the example above I am using a wordpress site with one of the default themes, but this same behaviour can be seen on any site that you load the Tag Manager preview in:
![image](https://user-images.githubusercontent.com/20905821/157788239-5653b713-b8b3-4ad2-b5d0-cad303f1e141.png)
![image](https://user-images.githubusercontent.com/20905821/157788302-6403b3ba-9411-4fbd-b9b1-1f0f4c452b06.png)
(Google was one of the few pages that didn't block me inserting my Tag Manager on its page)

**Comment by tsteur** [comment] 2022-03-11 02:18
@Starker3 is this a duplicate of https://github.com/matomo-org/tag-manager/issues/271 ?

**Comment by Starker3** [comment] 2022-03-11 02:28
Looks like it is (Although that one looks like a feature request rather than a bug report).

I have actually created a temporary fix for anyone that has this issue to implement it within the Tag Manager itself using a Trigger with a filter and a Custom HTML tag to add a margin to the footer element (It won't work in all cases, but it worked for the one users website that I tested it with and my own wordpress site).

Since someone might search for and find this bug report, I'll post that solution here:

1. Create a new trigger that will only be triggered when we have the preview mode enabled (Using the URL parameter):
![image](https://user-images.githubusercontent.com/20905821/157790115-a2d5efde-d0b8-4fa0-bb71-1a6a8016fb0f.png)

As you can see, we have a filter that will only allow this to trigger when the URL contains `mtmPreviewMode=`

2. Create a Custom HTML tag to adjust the footer element to place it above the preview mode box and set it to fire with our "Preview Pageview" trigger:
![image](https://user-images.githubusercontent.com/20905821/157790263-ca5c6daa-c2b8-400e-9c4b-d65f71463ca0.png)

The code that I have in the Custom HTML tag is as follows:
```
<script>
var footer = document.getElementsByClassName('footerClass');
  for(i = 0; i < footer.length; i++) {
    footer[i].style.marginBottom = '15%';
  }
</script>
```

It didn't work on all footer elements, which is why it uses a class selector. I also have not tested it on a lot of different resolutions, but it should work in 2560x1440 as well as 1920x1080 for most sites.

**Comment by tsteur** [comment] 2022-03-11 02:32
Great 👍  Nice workaround. I'll close it for now as a duplicate of https://github.com/matomo-org/tag-manager/issues/271 let me know if it's not the same.

**Closed as completed by tsteur** 2022-03-11 02:32 UTC
Labels: duplicate

**Comment by Starker3** [comment] 2022-03-11 02:33
If we do implement #271 then this shouldn't be an issue any more since people can change the position. But It might be easier to fix the z index issue rather than create a feature such as that one since it'll be probably a lot more work.

**Comment by tsteur** [comment] 2022-03-11 03:13
👍 @Starker3 I'm pretty sure this has always been the case re the overlaying etc. Not sure though how a z-index could fix it?

**Comment by Starker3** [comment] 2022-03-11 03:22
I don't know why I thought this was z-index related. That was my mistake.
